### ISSUE TITLE
No announcement before firing

### ISSUE THREAD

**Issue by Y0ungSandwich** [axle2005/ClearMob#12]
The cleared items announcement works but the warning one does not.
Version 1.3.2
spongeforge-1.10.2-2254-5.2.0-BETA-2264

```Clearing {
    CrashMode=false
    Interval=300
    KillAllMonsters=false
    KillAnimalGroups=false
    KillDrops=false
    Lists {
        EntityList=[
            "minecraft:zombie",
            "minecraft:witch",
            "minecraft:skeleton",
            "minecraft:creeper",
            "minecraft:arrow",
			"minecraft:redstone"
        ]
        TileEntityList=[
            
        ]
    }
    MobLimiter {
        Enabled=false
        Limit=500
    }
    PassiveMode=true
}
Warning {
    Enabled=true
    Messages {
        Cleared="[ClearMob] Endermen have removed mundane ground items"
        Warning="[ClearMob] Endermen removing mundane ground items in 1 minute"
    }
}
```

**Comment by axle2005** [comment]
I'm busy all day today and tomorrow, but Ill look into this on Friday. 

There wouldn't happen to be any error on the console when this tries to fire is there? 

3 notes: 

1. Awesome changing the message to Endermen have removed...
2. Did you know you could remove the [ClearMob] from the messages altogether and just have it print out: Endermen have removed mundane ground items
3. It also supports colors like: &9[&fDe&9V&fco&9]&r Entities have been cleared" (Outputs: [DeVco] Entities have been cleared) but in color.

**Comment by Y0ungSandwich** [comment]
I see no errors at all.

Thanks I figured it was fitting. I saw the prefix could be removed but figured leaving it might cause a little less confusion to users. 

Also if I wanted for example seeds to be removed from the ground they would go under entities or tile entities? Are there any wildcards say for a whole mod? Pam's harvest craft has a terrible habit of leaving seeds and vegetables all over the world. Im constantly finding them when Im exploring. Adding every item would be a long list lol.

**Comment by axle2005** [comment]
Please pick up the new version [here](https://ore.spongepowered.org/axle2005/ClearMob/versions/1.3.3)

**Comment by miladydreads** [comment]
I am still getting this problem with the newest version unfortunately.

**Comment by Y0ungSandwich** [comment]
Maybe something wrong with your syntax?  I dont remember if their is a config to turn the broadcaster on and off.  But mine is firing correctly.

**Comment by miladydreads** [comment]
Here is my syntax: 
Clearing {
    CrashMode=false
    Interval=900
    KillAllMonsters=false
    KillAnimalGroups=false
    KillDrops=true
    Lists {
        EntityList=[
            "minecraft:zombie",
            "minecraft:witch",
            "minecraft:skeleton",
            "minecraft:creeper",
            "minecraft:arrow"
        ]
        TileEntityList=[
            PlaceHolder
        ]
    }
    MobLimiter {
        Enabled=false
        Limit=500
    }
    PassiveMode=true
}
Warning {
    Enabled=true
    Messages {
        Cleared="[ClearMob] Entities have been cleared"
        Warning="[ClearMob] Clearing Entities in 1 minute"
    }
}

And I downgraded to the version he posted that said fixed the issue- waiting to see if it actually works now.

**Comment by miladydreads** [comment]
It worked with version 1.3.3!
