### ISSUE TITLE
No ListType config option

### ISSUE THREAD

**Issue by Y0ungSandwich** [axle2005/ClearMob#13]
I see in the wiki there should be a way to set the lists to black or whitelisting though I am not seeing anything in the actual config.

**Comment by axle2005** [comment]
With the additions of:
`    KillAllMonsters=false
    KillAnimalGroups=false
    KillDrops=false`
This whitelist/blacklist feature was removed. The same affect can be achieved by having them all set to true (to remove entities) or just define the list and have them all set to false. 

Of course, you can have those enabled and still have the list clearing entities on its own, for example, define a few mobs, then enable KillDrops.

**Comment by axle2005** [comment]
Additionally, the wiki is out of date. Ill update it hopefully soon. Thank you for bringing that to my attention.

**Comment by Y0ungSandwich** [comment]
Is there any method of wild carding an entire mod to be removed? We have Pam's Harvest Craft and its always leaving its fruits and seeds around the world.

**Comment by Y0ungSandwich** [comment]
Hmmm doing some testing and no items are being removed period. Listed or not. Only mobs, 
https://pastebin.com/wzJb0t0c

**Comment by axle2005** [comment]
Please try with the newest release. 
https://github.com/axle2005/ClearMob/releases/tag/1.3.4

You will need to run the server, and it will automatically populate your config with the changes, one of which is a ItemBlackList. Items on this list will not get removed when KillDrops is enabled.

**Comment by Y0ungSandwich** [comment]
Testing it now. Thanks for all the quick responses.

**Comment by Y0ungSandwich** [comment]
Will ground entities under Entity List get removed or am I mistaking this?

Because anything items, seeds, wool, etc,, aren't being removed with mobs.

**Comment by axle2005** [comment]
Anything that gets throw on the ground is considered an 'item' minecraft sees it specifically as minecraft:item. This is exactly what the new list is for. Anything you can throw on the ground goes in that list if you want it to survive.

**Comment by Y0ungSandwich** [comment]
Ah well that stinks lol. As you can imagine in a modpack like mine with 120+ mods there are a lot more items to keep vs those that wouldnt mind being cleared.

**Comment by axle2005** [comment]
I can certainly reverse it if you like, or add an option to reverse it, but I had modpacks in mind when I originally made this plugin. In my mind, there are very few things you actually want to keep lying around (Applied Energitics seeds being one of them)

**Comment by Y0ungSandwich** [comment]
That would definitely be helpful. Certain mods cause chickens to shed and drop fertilizer randomly, players and environment break gardens in the wild spilling out fruits and seeds, etc, etc, would love to be able to just clean all that up. We tried another mod that was similar to this and I gave up after 2 days of writing in mod items and mobs to keep lol.

**Comment by axle2005** [comment]
Try this release: 
https://github.com/axle2005/ClearMob/releases/tag/1.3.4.b

It will auto update your config, but it will be set to BlackList by default. This can be changed to whitelist and reloaded using /clearmob reload.

**Comment by Y0ungSandwich** [comment]
Working great! Is it possible to read from the oreDictionary?

EX: "ore:listAllfruit"

**Comment by axle2005** [comment]
Thats not something sponge is capable of. Sorry.
