### ISSUE TITLE
Clearing pets

### ISSUE THREAD

**Issue by fusionmc-evilscoop** [axle2005/ClearMob#14]
Seems every time the server restarts, my tamed mobs from mo creatures are getting culled....

Anyway to fix this ?

**Comment by axle2005** [comment]
Have you tried giving them names with a name tag?

**Comment by fusionmc-evilscoop** [comment]
they were all named
Im a twitch streamer, and each pet is named after a subscriber....sadly they all vanished after putting the plugin on, but they had been on a while
I tried using a chunk loader, this didnt help
I think it culls at server restart too as I have a regular restart at 2am set, but need to double check this

**Comment by axle2005** [comment]
What version are you currently using?

**Comment by fusionmc-evilscoop** [comment]
DrZharks MoCreatures Mod-10.0.6.jar
ClearMob-1.3.5.jar

**Comment by axle2005** [comment]
Alright... I do some testing on it, as it doesn't make sense... its doing a nametag check before doing anything else.

**Comment by fusionmc-evilscoop** [comment]
spawned a racoon, tamed it with steak, named it "edge" - in mo creatures you name on taming
racoon is in enclosure in a spawn area protected by grief prevention
Went to someones house many chunks away...did some bits for an hour, came back, racoon still there fine...
Restarted server
Racoon vanished :(

**Comment by axle2005** [comment]
So it sounds like its isolated to restarts... and you said this only happened when you installed clearmob? 

Also, could I see your config settings please.

**Comment by fusionmc-evilscoop** [comment]
[ClearMob.conf.txt](https://github.com/axle2005/ClearMob/files/1202150/ClearMob.conf.txt)
and thx for looking at this, all your plugins have been super usefull

**Comment by axle2005** [comment]
Can you try using this version? 
[2.0.0](https://github.com/axle2005/ClearMob/releases/tag/2.0.0)

**Comment by fusionmc-evilscoop** [comment]
certainly will...ill get back to you on this once ive tested it

**Comment by fusionmc-evilscoop** [comment]
I am sooo sorry.....ive just dug into this more since server was empty and i could do some reboots...

This was not a fault of clearmob
The pen for tamed animals is near spawn, with grief prevention running over it, with the claim flag set to entity-nospawn 
It would appear that the no-spawn flags, hits tamed creatures on startup.....need sub division to allow entities to spawn
Again im sorry i wasted your time here :(
even forcing a clearmob run entity the tamed mobs remain

**Comment by axle2005** [comment]
Pfft :P not a waste of my time... it made me get around to a huge rewrite I had intended on doing for a while... So much of ClearMob changed since the first commit, that code was becoming a mess and hard for even me to follow... This issue just made me finally get around to it.
