### ISSUE TITLE
unable to find the api7 build

### ISSUE THREAD

**Issue by ghost** [axle2005/ClearMob#18]
^^ thats all

**Comment by ghost** [comment]
31.10 12:39:33 [Server] Server thread/INFO [clearmob]: Configuration loaded.
31.10 12:39:33 [Server] Server thread/WARN [Sponge]: Plugin 'clearmob' is attempting to register command 'ClearMob' with an uppercase character - adjusting to 'clearmob'


this error comes with your latest version on api7 latest spongeforge 1.12

**Comment by axle2005** [comment]
I haven't even tried to move to 1.12 yet... does that still work besides the error <.<?

**Comment by ghost** [comment]
the plugin looks like its working

**Comment by LiskoSlayer63** [comment]
@axle2005 I can confirm that @ghost is wrong, it is **NOT** working on 1.12.2. It just says that it removed entities but nothing actually happens. Also it says the warning exactly same time it does the cleanup, not one minute before.

**Comment by unstablecraft** [comment]
are you planning to update to api 7 ???

**Comment by axle2005** [comment]
The network I'm with are in the process of starting into 1.12 projects. Which will include updating the plugins to work for it. This one will be included.

**Comment by axle2005** [comment]
API7 Release available here: [2.0.1](https://github.com/axle2005/ClearMob/releases/tag/2.0.1)

**Comment by unstablecraft** [comment]
Thank You  <3

**Comment by unstablecraft** [comment]
@axle2005  sorry for poking please add that admins have to add clearmob.admin to make the plugin work this is currently missing from your wiki 

thank you
