### ISSUE TITLE
Whitelist instead of Blacklist

### ISSUE THREAD

**Issue by Whazaaaaa** [axle2005/ClearMob#19]
Hai.

I was wondering if it was possible to have an option between whitelist and blacklist. How it works now is you remove the items specified in the list. But what I'd rather want is for items in that list to stay and all the other items to be removed. Otherwise I would have to make a weird huge list of items I want to keep when it would be much easier to just whitelist the one I would like to stay.

Thank you

**Comment by Whazaaaaa** [comment]
And is it possible ot use wildcard like minecraft.* or something?

**Comment by axle2005** [comment]
No. I already had whitelist and blacklist once, and it was removed... I am not going to re add it.

**Comment by Whazaaaaa** [comment]
Why was it removed :(?
