### ISSUE TITLE
[1.12.2] Crash message on startup

### ISSUE THREAD

**Issue by LiskoSlayer63** [axle2005/ClearMob#20]
ClearMob causes a single crash message when server is starting. This isn't crashing the whole server but I think that this isn't a normal behavior.

**ClearMob version:** 2.0.1
**SpongeForge version:** 2555-7.0.0-BETA-2764
**Forge version:** 14.23.1.2561
**Minecraft version:** 1.12.2

I uploaded the full crash message [here](https://pastebin.com/3zu8yKwF).

**Comment by axle2005** [comment]
Alrighty, Ill have a look. Thanks.
