### ISSUE TITLE
[1.12.2] How to configure and minor bugs

### ISSUE THREAD

**Issue by LiskoSlayer63** [axle2005/ClearMob#21]
I want it to remove all ground items _except_ those on the list. For now it works inverted, it removes only those which are on the list. I have a modded sdrver with over 2500 items so I just can't add everything to the list.

Also, none of the commands are working and the startup error is still there.

**ClearMob version:** 2.0.1
**SpongeForge version:** 2586-7.1.0
**Forge version:** 14.23.1.2586
**Minecraft version:** 1.12.2

**Comment by axle2005** [comment]
Are you sure you picked up the right version for 1.12? 

Anyway, I will not doing anything about this until you provide a config for the plugin and a forge log.

**Comment by LiskoSlayer63** [comment]
I'm pretty sure, I opened the mcmod.info and it said 1.12-2.0.1 for Sponge 7.0.0.  I'll upload the error when I can, I'm using my phone's TeamViewer at the moment to get information from the server so can't copy from the console so easily.

My config file:

```
{
  "mobLimiter": [
    {
      "limit": 300,
      "enabled": true
    }
  ],
  "options": [
    {
      "killAllMonsters": true,
      "killAllDrops": true,
      "listItemEntitys": [
        "minecraft:redstone",
        "minecraft:diamond",
        "minecraft:coal",
        "minecraft:emerald"
      ],
      "killAnimalGroups": true,
      "listEntitys": [
        "minecraft:zombie",
        "minecraft:witch",
        "minecraft:skeleton",
        "minecraft:creeper",
        "minecraft:arrow"
      ],
      "listTileEntitys": [
        "PlaceHolder"
      ]
    }
  ],
  "warning": [
    {
      "message": "[ClearMob] Clearing Entities in 1 minute",
      "enabled": true
    }
  ],
  "passive": [
    {
      "interval": 1200,
      "message": "[ClearMob] Entities have been cleared",
      "enabled": true
    }
  ]
}
```

**Comment by axle2005** [comment]
https://gist.github.com/axle2005/3be7319e4aae80df96e1786438dc2628

**Comment by LiskoSlayer63** [comment]
I'm updating this issue because I just updated SpongeForge and ClearMob, but it is still not working properly. I really love what this is supposed to do, but I think it does nothing at the moment.

**EDIT:** I can confirm that this plugin does _nothing_ right now. @axle2005 can you possibly fix it?

**ClearMob:** 1.12-2.0.1
**SpongeForge:** 2768-7.1.5
**Forge:** 14.23.5.2814
**Minecraft:** 1.12.2

Configuration is identical to the previous one.

Crash message on startup: https://gist.github.com/LiskoSlayer63/5fd25ceec37773f85c0812a4901cd8da
Crash message on clear: https://gist.github.com/LiskoSlayer63/f1212b5fed40974101e94858b46d2735
