### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Wissi** [axle2005/ClearMob#26]
Was working fine when first installed. Then stopped working. Not displaying the msgs of "clearing in 60 secs" or the "entities cleared". Even after server restart.
When manually running the command `/clearmob run entity` it doesn't work and gives an error in console. Error [here](https://gist.github.com/Wissi/786842d52d0f5092bdf99d5b899d06db).

Using:
ClearMob-1.12.2-2.2.0
spongeforge-1.12.2-2825-7.1.6-RC3693
forge-1.12.2-14.23.5.2836-universal

On Minecolonies Official Server. Modpack info [here](https://minecraft.curseforge.com/projects/minecolonies-testpack/files/2708722) if needed.

Thanks.

**Comment by axle2005** [comment]
I type up a response to this earlier... and poof... gone... thanks Microsoft...

Anyway, can you please upload your config file, as well as a copy of the server log that includes the entire startup? The only thing in the code that could really error at that point is it not loading the config successfully

**Comment by Wissi** [comment]
Sure, I do see that there is a "problem reloading Config".
This is the Server log: [latest.log](https://github.com/axle2005/ClearMob/files/3164264/latest.log)
Config file: 
[ClearMob.json.txt](https://github.com/axle2005/ClearMob/files/3164267/ClearMob.json.txt)
(had to add .txt so it could upload due to githubs limits)

thank you so much for such a quick reply.

**Comment by axle2005** [comment]
I just uploaded a new version to Ore... although I was unable to reproduce the NullPointerException, even with your config.
