### ISSUE TITLE
Applying for a reprint permission.

### ISSUE THREAD

**Issue by jwjoel** [axle2005/ClearMob#30]
Thanks for your contribute! The plugin is what I'm looking for, which helps a lot. Whether can I reprint the plugin to another forum that is the most famous in China with all copyright information? Waiting for your reply :)

**Comment by axle2005** [comment]
I mean... does China not have access to Ore? You could make a redirect page to Sponge Ore page.

**Comment by jwjoel** [comment]
Yeah we can access to Ore and sure I'll make a redirect to Ore page, but I need to share some basic information about the plugin on the forum and then I'll direct our uses to Ore page to download, how about this :)

**Comment by axle2005** [comment]
That's acceptable

**Comment by jwjoel** [comment]
Thanks!
