### ISSUE TITLE
Does not work Warning Message 

### ISSUE THREAD

**Issue by 10menbey** [axle2005/ClearMob#32]
Does not work Warning Message although` the conception is true
Version (1.12.2-2.2.3)

`[16:16:27] [pool-3-thread-3/INFO] [clearmob]: 0 Entity were removed
[16:16:27] [pool-3-thread-3/INFO] [clearmob]: 0 Tile Entity were removed
[16:16:27] [pool-3-thread-3/INFO] [minecraft/DedicatedServer]: [ClearMob] Entities have been cleared
[16:17:27] [pool-3-thread-3/INFO] [clearmob]: 0 Entity were removed
[16:17:27] [pool-3-thread-3/INFO] [clearmob]: 0 Tile Entity were removed
[16:17:27] [pool-3-thread-3/INFO] [minecraft/DedicatedServer]: [ClearMob] Entities have been cleared`

**Comment by axle2005** [comment]
Whole config please and sponge version

**Comment by 10menbey** [comment]
forge-1.12.2-14.23.5.2838-universal
[{
  "General Options": [
    {
      "Dropped Items Blacklist": [
        "minecraft:redstone",
        "minecraft:diamond"
      ],
      "Entity Whitelist": [
        "minecraft:boat",
        "iceandfire:firedragon",
        "iceandfire:icedragon",
        "battletowers:golem"
      ],
      "Enable Kill All Monsters": false,
      "Enable Kill All Dropped Items": true,
      "Enable Kill All Bosses": false,
      "Enable Kill Grouped Animals": false,
      "Tile Entity Whitelist": [
        "PlaceHolder"
      ]
    }
  ],
  "Mob Compression": [
    {
      "Enable for Animals": false,
      "Enabled": true,
      "Enable for Monsters": true
    }
  ],
  "Passive Mode": [
    {
      "Interval in Seconds": 3600,
      "Message to Players": "&c&l[&6&lRoma&c&l] &3&lВсё больше нету ни лута&d&l=>",
      "Enabled": true
    }
  ],
  "Warning Message": [
    {
      "Message to Players": "&c&l[&6&lRoma&c&l] &3&l Лут станет мои за 1мин",
      "Enabled": false
    }
  ],
  "Mob Limiter": [
    {
      "Max Limit": 500,
      "Enabled": true
    }
  ]
}
](url)

**Comment by axle2005** [comment]
Warning message is set to false in that config...
