### ISSUE TITLE
Feature & question

### ISSUE THREAD

**Issue by bigenergy** [axle2005/ClearMob#34]
Hi, I suggest adding a setting to prevent the removal of entities with a tag.

Also, I have a question, how to prevent the removal of item frames and armor stands in the config?

**Comment by axle2005** [comment]
That feature is already part of it... 

And I don't know off the top of my head what Item Frames/Armor stands are... if they are Entities, its entity-b-minecraft:(Whatever the item is), otherwise tileentity-b-minecraft:(whatever it is)

**Comment by bigenergy** [comment]
@axle2005 i use "entity-b-minecraft:armor_stand" and "tileentity-b-minecraft:armor_stand", but the armor stand is still removed

**Comment by bigenergy** [comment]
@axle2005 pls help

**Comment by bigenergy** [comment]
@axle2005 hey..
